"""init database

Revision ID: a76bf4be65c1
Revises: 
Create Date: 2025-03-19 21:35:14.304127

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy_utils import ArrowType
import sqlalchemy_utils
import sqlmodel.sql.sqltypes
# revision identifiers, used by Alembic.
revision = 'a76bf4be65c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('short_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('expiration_date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_urls_short_url'), 'urls', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
